Feature/5 data source service
airavata-courses/DCoders pull request #14
Opened 2022-02-03 08:37 UTC by vinayakasg18

- Initial code for the review
- DO-NOT merge. Clean and optimization are pending.

2022-02-06 06:18 UTC, ChaitanyaD20 requested changes
I have pointed out a few minor issues. Kindly have a check for the same.

Thank You

Chaitanya

2022-02-06 06:18 UTC, ChaitanyaD20 commented on workflow_templates.sh
> +    echo "${WORKFLOW}" > .github/workflows/${APP}.yaml
Looks like this going to create a workflow for the files as well. Could you please cross check once.

2022-02-06 06:18 UTC, ChaitanyaD20 commented on datasource_service/tests/test_main.py
> +
Looks like a test case is missing for the function: download_radar_object. Could you please add some for the same. It will be great to debug then.

2022-02-06 06:18 UTC, ChaitanyaD20 commented on datasource_service/datasource_service/main.py
> +
Could you please remove the commented code, so that it becomes clean.

2022-02-06 09:31 UTC, SwetShah requested changes

2022-02-06 09:31 UTC, SwetShah commented on .github/workflows/workflow-template.yaml
> +        password: 9b770f15-c13f-41cd-a4df-6a1a175141a6
Can we externalize this to the secret manager?

2022-02-06 09:31 UTC, SwetShah commented on datasource_service/README.md
> +    ``` docker run {docker-image} ```
Kindly mention the repository to pull the image from

2022-02-06 09:31 UTC, SwetShah commented on datasource_service/datasource_service/main.py
> +""" Microservice to fetch nexrad data from aws s3 """
Can we add the loggers for upcoming milestones

2022-02-06 09:35 UTC, SwetShah approved these changes

2022-02-07 16:19 UTC, vinayakasg18 commented
Thanks for the review. Merging the PR.

2022-02-07 16:20 UTC, merged